name: "Extension upload"
on:
  push:
    branches:
      - master
      - workflow

jobs:
  upload:
    name: Extension upload
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      APP_ID: lejaemboagmjemhpniglggbmdajgmeln
    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: npm build
        run: npm run build
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./qr-extension.zip ./dist
      - uses: actions/upload-artifact@v2
        with:
          name: qr-extension
          path: ./qr-extension.zip
      - name: Upload extension
        uses: Klemensas/chrome-extension-upload-action@v1.3
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          app-id: ${{ env.APP_ID }}
          file-name: ./qr-extension.zip
