name: "Extension upload"
on:
  push:
    tags:
      - v*
jobs:
  UploadExtension:
    name: Extension upload
    runs-on: ubuntu-latest
    env:
      APP_ID: lejaemboagmjemhpniglggbmdajgmeln
    steps:
      - uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./qr-extension.zip ./dist
      - name: Upload extension
        uses: Klemensas/chrome-extension-upload-action@v1.3
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          app-id: ${{ env.APP_ID }}
          file-name: ./qr-extension.zip
